### ISSUE TITLE
Create vesting for BSX reward for HDX holders

### ISSUE THREAD

**Issue by timbo-timboa** [galacticcouncil/Basilisk-crowdloan-ui#26]
- [x] -> calculate BSX reward for HDX holders at block #1999999 
- [x] -> api.query.system.accounts.entries.at()
- [x] -> discard treasury and intergalactic acc
- [x] -> calulate 5 000 000 000 proportional to holdings at the time for each holder
- [x] -> get vesting schedule details
- [x] -> review PR fix anything wrong

**Comment by timbo-timboa** [comment]
@lumir-mrkva @jak-pan @maht0rz 🙂 

What is timeline for this vest ?  Probably same as for the 70% of BSX from last vest  ?

**Comment by timbo-timboa** [comment]
there are 7 addresses with zero balance.  Just FYI

```js
accts w zero balance:  [
  '7LTEm9QYCYRsWG7AuuRCgjL5L6SDxPssHPrVJE4WmaLRJ7J3',
  '7KEn2siNKFqSVA9dDntb98fy3iFB8BzmzQzVRiMhH6LrApH3',
  '7LxVQ6cG1JMy6ZXf4NSKU8yydWe9GBudSgbpeAxmmTpvKHgs',
  '7LbhZw718oe8vQDzbLPGaFEx1V6eS3Nf2UBocVcaHrfGKqn2',
  '7Ms5LgffWaUZRKbza9chqF4D6uZZhMkdHiuMJbovpVaMwirH',
  '7NYhFJKwDx2SBPyMgx5wHP3mhSQLVEfUmwyb535MMKoSXqGg',
  '7KgX8hfogFwMczasWj686p92jgbrwVYdNYRo6N9nyz7oiseG'
]
```

☝️  filter these out or nah ?

**Comment by timothydm42** [comment]
> ```js
> 7KEn2siNKFqSVA9dDntb98fy3iFB8BzmzQzVRiMhH6LrApH3
> ```

We elected to delete vesting schedules for these address,  because the vesting schedules are empty.

**Comment by timbo-timboa** [comment]
> ```js
> accts w zero balance:  [
>   '7LTEm9QYCYRsWG7AuuRCgjL5L6SDxPssHPrVJE4WmaLRJ7J3',
>   '7KEn2siNKFqSVA9dDntb98fy3iFB8BzmzQzVRiMhH6LrApH3',
>   '7LxVQ6cG1JMy6ZXf4NSKU8yydWe9GBudSgbpeAxmmTpvKHgs',
>   '7LbhZw718oe8vQDzbLPGaFEx1V6eS3Nf2UBocVcaHrfGKqn2',
>   '7Ms5LgffWaUZRKbza9chqF4D6uZZhMkdHiuMJbovpVaMwirH',
>   '7NYhFJKwDx2SBPyMgx5wHP3mhSQLVEfUmwyb535MMKoSXqGg',
>   '7KgX8hfogFwMczasWj686p92jgbrwVYdNYRo6N9nyz7oiseG'
> ]
> ```


We elected to delete vesting schedules for these address,  because the vesting schedules are empty.

**Comment by jak-pan** [comment]
> ```js
> ```js
> accts w zero balance:  [
>   '7LTEm9QYCYRsWG7AuuRCgjL5L6SDxPssHPrVJE4WmaLRJ7J3',
>   '7KEn2siNKFqSVA9dDntb98fy3iFB8BzmzQzVRiMhH6LrApH3',
>   '7LxVQ6cG1JMy6ZXf4NSKU8yydWe9GBudSgbpeAxmmTpvKHgs',
>   '7LbhZw718oe8vQDzbLPGaFEx1V6eS3Nf2UBocVcaHrfGKqn2',
>   '7Ms5LgffWaUZRKbza9chqF4D6uZZhMkdHiuMJbovpVaMwirH',
>   '7NYhFJKwDx2SBPyMgx5wHP3mhSQLVEfUmwyb535MMKoSXqGg',
>   '7KgX8hfogFwMczasWj686p92jgbrwVYdNYRo6N9nyz7oiseG'
> ]
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> We elected to delete vesting schedules for these address,  because the vesting schedules are empty.
> ```

Why is it empty?
