### ISSUE TITLE
Restyle UI for HydraDX

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-crowdloan-ui#29]
- Rename KSM to DOT
- Restyle CSS as hydradx.io or [figma](https://www.figma.com/proto/b6irRFY0t1paG3zkUHfGmH/HydraDX?node-id=1360%3A5050&scaling=min-zoom&page-id=1222%3A6)
- get rid of all BSX references (inputs, displays)

**Comment by mrq1911** [comment]
moved to forked repo https://github.com/galacticcouncil/HydraDX-crowdloan-ui
